### PR TITLE
fix: remove unused `lib.rs` file

### PR DESCRIPTION
**Pull request by EstebanBorai**
Removes what it looks to be an unused file (`lib.rs`). Checking though the
source I didn't found any modules using this file neither a purpose in the `Dockerfile`.

### CODE REVIEW

**Comment by calebcartwright** [comment]
Thanks so much for the contribution! The file is indeed currently unused, although it is intentional. I'd hoped to use the lib target to expose some of the functionality for integration testing, but unfortunately haven't had the time to get around to it.

Let me know if that's something you'd have any interest in taking a crack at, as I'd be happy to lay out the broad strokes

**Comment by EstebanBorai** [comment]
> Thanks so much for the contribution! The file is indeed currently unused, although it is intentional. I'd hoped to use the lib target to expose some of the functionality for integration testing, but unfortunately haven't had the time to get around to it.
> 
> Let me know if that's something you'd have any interest in taking a crack at, as I'd be happy to lay out the broad strokes

Hey @calebcartwright! Yeah I would love to help!

Is there any issue I can take for this? Thanks in advance!

**Comment by calebcartwright** [comment]
Excellent @EstebanBorai! I'll write up the details in a new issue at some point over the coming days and will tag you for awareness in case you want to try to tackle it

**Comment by EstebanBorai** [comment]
> Excellent @EstebanBorai! I'll write up the details in a new issue at some point over the coming days and will tag you for awareness in case you want to try to tackle it

Of course! Thanks so much!

**Pull request closed without merging**
